

CREATE TABLE IF NOT EXISTS system_metadata (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_key    VARCHAR(255) NOT NULL UNIQUE,
    meta_value  TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO system_metadata (meta_key, meta_value)
VALUES ('schema_version', '1.0.0');
